version: '3.9'

services:
  app_prod:
  backend:
    container_name: nestjs-app-prod
    build:
      context: .
      dockerfile: Dockerfile-be
      target: prod
    ports:
      - "3001:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-fe
      target: production
    ports:
      - "80:80"
#DB...