version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: nestjs-app-prod

#DB...

    ports:
      - "3001:3000"
    command: node dist/main.js
